### ISSUE TITLE
Feature: Browser equivalence

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/modules#133]
Whenever Node.js is doing something with modules that browsers also do, Node.js and browsers do it the same way.

Use case 60.

**Comment by SMotaal** [comment]
I guess I did not see this when I opened #136 but this is exactly what I was exploring over the past several months, and very extensively most recently.

So the short of #136 is that should the current state of experimental modules not address "bare" specifiers, foremost, not to diminish from the importance of other interop aspects, releasing will most likely see people struggling to create ECMAScript modules that can be imported (ie does not throw uncatchable errors) across both paradigms. Emphasis is node's compatibility with browser norms, at least from developer's perspective due to untameable browser-restrictions compared to the greater reach and tooling possible in node. We have the honour and burden of provide a good narrative to this 😁.

**Comment by guybedford** [comment]
I'd like to mark this as a duplicate of #107. I think it's clear that like Node we will follow the browser where necessary, and I think this is a fundamental requirement for #107 anyway.

**Comment by guybedford** [comment]
Otherwise we could do this the other way around, and add to this feature "including the ability to have code that runs in both environments without a build".

**Comment by GeoffreyBooth** [comment]
This is broader than #107, so that would be included in this one. But this feature is basically a meta-feature like spec compliance, that's so broad it could encompass almost anything. I think we should keep them both open, as the specific ask in #107 would get lost in here; but we need to keep this as a top priority feature in its own right.
