### ISSUE TITLE
Having a meeting this week ~ Wednesday

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#189]
What time would work for y'all? I'm booked from 3pm - 4pm (our usual time).

Does 4pm work for people?

**Comment by ljharb** [comment]
4PM ET/1PM PT works for me.

**Comment by benjamingr** [comment]
I'm back from holiday (yay) - either 4pm ET or the regular time works for me

**Comment by MylesBorins** [comment]
Let's assume we are meeting tomorrow at 4pm ET!

**Comment by bmeck** [comment]
I won't be able to make it, but have nothing of note to report. I'm currently talking with the security WG about how loaders might be affected by security policies but it is still in transition. Since there is a need for SRI etc. separate from how modules are loaded I'm also talking about policies there.

**Comment by benjamingr** [comment]
@MylesBorins is the meeting happening? If so - is there an issue for it/zoom link?

**Comment by MylesBorins** [comment]
https://github.com/nodejs/modules/issues/190
