### ISSUE TITLE
When should we drop the moratorium?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#225]
If we are convinced that we will build off the minimal kernel and have an idea of what the future looks like at what point does it make sense to upstream?

The longer we allow the current implementation to continue to exist in the wild the more there will be code that relies on it.

We could also upstream to master / Current but not LTS

**Comment by devsnek** [comment]
i would say we should upstream as soon as we have functionality which matches or exceeds the current upstream

**Comment by GeoffreyBooth** [comment]
I concur with @devsnek. We’ll be well on our way (but probably not quite there yet) by the end of Phase 2.

If we think that upstreaming the new implementation is very likely to happen, and I don’t see why it wouldn’t, we could consider updating the Node docs now to add some warning that there’s a good chance that `--experimental-modules` might be replaced with a different implementation and public API in the near future.

**Comment by devsnek** [comment]
> we could consider updating the Node docs now to add some warning that there’s a good chance that --experimental-modules might be replaced with a different implementation and public API in the near future.

fwiw, that's literally why node has experimental flags, so i don't think that's needed

**Comment by GeoffreyBooth** [comment]
I agree it _shouldn’t_ be needed, but I think @jdalton can provide several anecdotes of having to guide people toward stopping using `--experimental-modules` in production or in public (non-experimental) build tools. I used it myself for a real-world application before joining this group, because I assumed it meant that the feature was in beta. Clearly the message isn’t getting across to a sizable number of users that they shouldn’t be using it. I don’t think being more explicit in the docs could hurt.

**Comment by mcollina** [comment]
I think we should send a PR to master from this repo as soon as possible, and ship it in v11. I think some people are settling in using `--experimental-modules`, and we should be _breaking_ them as soon as possible.

I would recommend for the majority of the work to keep being done in this repository, and just do a PR once and then when there is consensus here.

**Comment by guybedford** [comment]
My main issue with shipping the minimal implementation as-is is that currently `--loader` opens up a lot of ways for users to tailor modules in Node to their own needs. Because this minimal implementation has removed `--loader` I feel that taking that away stops that sort of community experimentation, which is important.

**Comment by SMotaal** [comment]
I also agree with @guybedford on the `--loader` aspect. I wonder if we want to consider if the `--loader` flag can be made functional on top of the new implementation if and only if it is used with `--experimental-modules` flag.

I am not able to infer if the intent is to retain needing `--experimental-modules` when landing this unfinished minimal implementation but made the assumption, am I right?

**Comment by MylesBorins** [comment]
Closing for now. We can revisit a bit later when we have a clearer vision
