### ISSUE TITLE
Module loaders memory issue?

### ISSUE THREAD

**Issue by zenparsing** [nodejs/modules#272]
@bmeck In the previous call, you mentioned briefly a memory issue with module loaders. I'm curious; can you elaborate?

**Comment by bmeck** [comment]
@zenparsing sure. I'll try and explain, but it is kind of non-obvious on a glance. Note, this affects Loaders no matter what Realm/Agent/etc. they are in that I can tell; it is a symptom of allowing cyclical synthetic modules and resolving to synthetic modules.

----

Loaders should be able to create synthetic cyclical module graphs. Consider:

```mjs
// a
import 'a';
```

This is the base case of a cyclical module graph. Where `a` -> `a`. In order to allow this we need to create a Location for a prior to it instantiating or evaluating. This graph could be loaded by:

```console
node --loader foo a
```

This would result in 2 resolve operations which are approximately:

```mjs
a = resolve('a', cwd);
a = resolve('a', a);
```mjs

We need to have a able to be referenced prior to being linked. This would be a problem for APIs needing the references prior to construction like:

```mjs
a = new Module(src, {a: _});
```

This results in a thunk based approach to allow initialization to be separated from instantiation:

```mjs
a = new Module(src, (specifier) => specifier === 'a' ? a : null);
```

This approach uses a reference to `a` in memory that keeps the Module alive. Unlike a constructive/reflective API in this example, Loaders operate both in isolation and in reaction to existing modules. This makes there API more similar to:

```mjs
resolve(specifier, referrer) {
  if (referrer === a) return a;
  return getSourceFor(parent.resolve(specifier, referrer));
}
```

Being called with:

```mjs
resolve('a', a);
```

However, such an API design leads to needing to keep a reference to a alive via a closure until it can no longer be resolved. That is where we encounter the real problem. The reference `a` that is kept in the closure must coordinate with the Agent holding the Module in order to agree that it will never be referenced again. This dance ~= some form of:

1. If the Agent no longer directly holds a Module:
    1. Notify that Loader that the Module is ready to be GC'd.
    1. If the Loader can no longer resolve to a Module:
        1. GC the Module.

This means that Loaders need to be notified when an Agent is ready to GC a Module and have the ability to refuse allowing a Module to be GC'd.

This has a few caveats though:

* Loaders that keep a Module alive, keep the entire Realm containing the Module alive (and potentially all reference-able modules in that Realm).
* The referrer parameter keeps Modules alive and direct references to it need to be carefully managed. This value should be idempotent as long as the Module is alive outside the loader since it could be stored in a WeakMap if it uses GC semantics or it must be idempotent forever if it is forgeable via means such as string manipulation (this is the same leaking problem that [URL.createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) has).

This results in a few new design caveats:

* Module references must not use naive GC semantics
    * If they do use GC, either:
        * Guarantee a means of notifying them for finalization but allowing revival (this encounters all the classic revival design considerations T_T)
        * Ensure that strongly holding the Module reference can be done weakly rather than directly (only expose them through mechanism like [WeakRef](https://github.com/tc39/proposal-weakrefs).prototype.deref() ???).
* Module references not be forgeable.
    * Really.

**Comment by MylesBorins** [comment]
Closing this as there has been no movement in a while, please feel free to re-open or ask me to do so if you are unable to.
