### ISSUE TITLE
A New Field Proposal

### ISSUE THREAD

**Issue by WebReflection** [nodejs/modules#298]
If `module` is off the table, maybe we could just agree on a new field that everyone could start adopting as soon as they'll start eventually adopting the `type` field in `package.json`.

Following some name I wouldn't care/mind adding in my published module to keep backward compatibility and future one:

  * `entry-file`, only if `--entry-type` flag will make it though - vote via 👍
  * `type-entry`, since `type` is already decided, hence reserved, let's use it as prefix - vote via 🎉
  * `type-main`, just to simplify the understanding of what it is (the `main` for the specific `type`) - vote via 🚀

These names are generic on purpose, so that no `module` or `commonjs` or `wasm`, or whatever the future reserves, will be compromised.

The logic is simple:

  * if there is a `type` field in the `package.json`
    * if there is a `type-entry` field, use it as module entry point
    * otherwise fallback with `main` or whatever current mechanism we have

This will be also valid for `"type": "commonjs"`, so that a module can be scoped as CJS, but babel users will still be able use the `module` field.

Thanks for considering this, I've also put the emoji poll in place

P.S. feel free to like this comment via ❤️

**Comment by devsnek** [comment]
the type field doesn't have much to do with having multiple entrypoints.

**Comment by WebReflection** [comment]
> the type field doesn't have much to do with having multiple entrypoints.

I don't understand this comment.

This proposal is about allowing dual modules. The `type` field specifies the mode that `browserify` or other tools might completely ignore.

If they do, the `type` field set as `module` with a `main` file that cannot be parsed by, as example, browserify, will break everyone using browserify.

So, while the `type` field will have strictly nothing to do with dual modules, if there's no way to specify a different entry than `main` no dual package is possible.

This is about **baclward compatibility**, it's not about changing the `type` field meaning.

It's a proposal to simply migration pattern for people that already published dual modules to date.

**Comment by GeoffreyBooth** [comment]
How does this differ from #273, aside from the name of the field?

**Comment by WebReflection** [comment]
@GeoffreyBooth 

  * it doesn't seem to differ
  * you asked me to file a new issue 😅

We can close it if the purpose of #237 is the same 👋

**Comment by GeoffreyBooth** [comment]
So the entry point of the _application_ and the entry point of the _package_ are quite different things. The `--type` flag always only applied to the former, never the latter. The latter is what `require('package-name')` or `import 'package-name'` map to, and since it’s being referenced from `require` or `import` we already know the intended mode that the importing code wants. (The caveat there is that `import` wants to import ESM into ESM, but if the package only has CommonJS, it’ll import CommonJS into ESM.)

The entry point of the application, on the other hand, is what you call the `node` command to run. The `node` command by itself doesn’t inherently mean one type or another, so we need some way to determine the type: file extension, if the file ends in `.mjs` or `.cjs`; `package.json` `"type"` field if there is one; or (currently) `--type`/`--entry-type`.

The debate between `--entry-type` and `--package-type` is that `--entry-type` sets the type of that single file, but not any other files that it may import; and that goes against a lot of people’s expectations. An `import` can bring in _either_ ESM or CommonJS, even on the individual file level, and so `import 'file.js'` loads `file.js` based on the nearest controlling `package.json` `"type"` field, regardless of however the application entry point was loaded. The issue is that people have reservations about making the flag apply to the entire scope, the way a `"type"` field would, but conversely users aren’t expecting the entry-only behavior (even if we name the flag `--entry-type`).

Either way, setting the entry point of a _package_ is separate. It’s not possible to have a useful package with an ambiguous entry point file, since a useful ESM package presumably exports something, and therefore needs to use the `export` keyword which would throw in CommonJS mode. So we need two separate files for the two entry points for ESM and CommonJS. Proponents of extension searching (and `.mjs`) want to use `"main"` for this, and have a field like `"main": "./index"` where either `index.js` or `index.mjs` are loaded based on extension searching based on whether the package is being `import`ed or `require`d. Others want to use a separate field, like `"module"`, so that users can have the separate entry points in separate folders (and possibly both with `.js` extensions, should the user want that). Either way though, by definition the entry point is tied to a module format, and so there’s no need to “set” the type of a package entry point; all the `"type"` field does is set the type of `.js` files in the package scope.

**Comment by GeoffreyBooth** [comment]
> We can close it if the purpose of #273 is the same 👋
> 
> P.S. this proposal doesn’t relate the entry field with any parse goal type though …

Oh I didn’t mean to imply that this issue shouldn’t be here, I just wanted you to elaborate on how it differed besides the name of the field. If all you wanted was `"exports"` renamed, sure, that makes sense to me to keep in the other issue, as that’s a criticism of that proposal; but I thought you were proposing different functionality.

**Comment by WebReflection** [comment]
> I thought you were proposing different functionality.

The fact we need long posts to describe differences against developers expectations means things aren't shining too much in here ... anyway, this is what I'd expect in a nutshell

If I explicitly ask node to load a file I explicitly pass, I expect to be able to tell node I want that file to be treated as the given type, and everything after should be work accordingly, s if it was the entry point of any module with such type specified.

This is the obvious least surprise, 'cause no real-world use cases exist for any other behavior to expect.

**example**
```js
node --entry-type=module mindyourbusiness
```

The `mindyourbusiness` is clearly an ESM module, if not it should throw on require as expected.

Since the dev intent was to force it to be ESM, there is no reason to not act as one, so that everything it imports, beside explicit `.cjs`, should be handled as if it was an ESM module with a type module.

Same goes if commonjs was specified as target, everything imported, unless `.mjs` iso explicitly used, should be defaulted as CommonJS.

However, as I understand, that' s not how `--entry-type` will work.

So, considering current proposed `--entry-type` a dead useless end, all I'd like to preserve is the ability to have dual modules.

I've already written examples and I'll write it again:

```js
{
  "main": "./cjs/index.js",
  "module": "./esm/index.js",
  "type": "module"
}
```

I want above package.json to let every current nodejs in this world to load it as commonjs, but I want every modern version of node, compatible with native ESM, to load that module as ESM.

This shouldn't be too difficult to understand, but it's practically impossible with the current status.

This proposal, in case `module` field cannot be used, even if the reasoning is not actually a real blocker, is to have a new field that will let **modern** installations of nodejs to use ESM version, no matter which extension it has, and still let every legacy version of node, and modules, to consume the regular CommonJS version.

The example `./esm/index.js` file should be loaded as ESM and every import in it should be loaded as ESM by default, unless the extension is `.cjs`, same as the `main` file would load everything as CommonJS, unless the extension is `.mjs`.

Having a global parsing goal is a constant / env variable, that I don't understand why is considered so complicated, so I hope, for the sake of not breaking dual modules, or making these practically impossible to use, that exports or whatever field name we chose, will land as well.

**Even with just main ...**

If the intent of having just "main" pointing at `./index` so that modern node will look for `.mjs` before `.js` and treat the whole module as ESM, if the `type` is `module`, would work, 'cause the work around to never write `.mjs` is to have an `index.mjs` that exports everything in `esm/index.js`, and an `index.js` that will `module.exports` what's in `cjs/index.js`, so that at the end of the day, `.mjs` will be used to disambiguate what a package field could do already, and we can happily move on with this whole story.

**Comment by GeoffreyBooth** [comment]
@WebReflection You’re conflating a user starting an application with a project including a package. The flag is only used for starting an application; `"main"` and/or any additional field like `"module"` is only used for including a package. There’s no overlap there.

If I run `node index.js` and there’s a `package.json` in the same folder or above as `index.js`, and that `package.json` has `"type": "module"`, then all the `.js` files in my project are treated as ESM. Done. There’s no need for a flag if one is willing to add the `"type"` field; `node index.js` will run that file as ESM without the flag, because the field is there. The only use case that _needs_ the flag is non-file inputs like `--eval`.

In the current implementation if my code has an `import` statement for a package, and that package has a `package.json` with `"type": "module"` and `"main": "./index.js"`, then that `index.js` will be loaded as ESM (as will any other `.js` file in the package). Trying to `require` the package will error, which is a problem we need to address; this is explained in the announcement post. Currently a package can be CommonJS _or_ ESM, but not both, from just the bare import; whereas with paths into the package you could have it both ways via stuff like `import 'pkg/src/index.js'` / `require('pkg/dist/index.js')`.

Yes we need to fix dual packages, and provide a way to do that, and I think having a separate field to define the ESM entry point is the solution that satisfies the most use cases including preserving backward compatibility and ESM/CommonJS files in separate folders. But that’s completely unrelated to the flag, and it’s not really related to the `"type"` field.

**Comment by WebReflection** [comment]
> The only use case that needs the flag is non-file inputs like --eval.

And standalone files

Anyway, if dual package without backward compatibility is possible with any other proposal, there's no need to keep discussing this. 👋

**Comment by GeoffreyBooth** [comment]
> And standalone files

Well, only standalone files that you don’t want to rename to `.mjs` or put into a folder with a `package.json`. I feel like it’s not very common for JavaScript files to be floating around without a `package.json`, where they use only builtin modules or globally-installed packages. Having to rename or move such files doesn’t seem too terrible to me.

And if we go the “for non-file inputs” route, where a flag like `--input-type` applies only to `--eval`, `--print` and STDIN, one could always do something like `cat loose-file.js | node --input-type=module`. Pretty hacky, but it would work.

> Anyway, if dual package without backward compatibility breaks is possible with any other proposal, there’s no need to keep discussing this. 👋

Yes, #273 is that.
