### ISSUE TITLE
V8 implemented Synthetic Module Record

### ISSUE THREAD

**Issue by targos** [nodejs/modules#345]
Is it something we would like to experiment with?

See https://github.com/v8/v8/commit/92147e3aca982c714e9b6a26e108889b8cd66073

**Comment by guybedford** [comment]
This will definitely be useful, and allow us to remove uses of the wrapper in https://github.com/nodejs/node/blob/master/lib/internal/modules/esm/create_dynamic_module.js making things much cleaner.

Note that the code above is effectively "feature-equivalent" so that this can be considered more of a refactoring / code improvement though I think.

**Comment by devsnek** [comment]
I wasn't able to figure out how to backport this directly but once we have it in node I'd be happy to write up the wrapper for it.

**Comment by MylesBorins** [comment]
AFAICT we've refactored on top of this closing
