### ISSUE TITLE
Can I be an observer?

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/modules#56]
Hi, I’m the maintainer of [CoffeeScript](https://github.com/jashkenas/coffeescript). I’d like to keep up to date with the plans for modules support in Node.

**Comment by MylesBorins** [comment]
Adding to the modules agenda so we can discuss adding observers at the next meeting. I'll see if I can come up with some process text for us to vote on.

**Comment by billinghamj** [comment]
I am also observing, but am doing that by just hitting subscribe on the repo. Maybe that’d meet your needs?

**Comment by MylesBorins** [comment]
@billinghamj being an `observer` generally afford people the ability to attend and participate in team meetings.

**Comment by weswigham** [comment]
Though we've ever turned anyone away or kept the meeting invite private, which means subscribing to the repo and clicking on the meeting invite links gets you pretty much everything.

**Comment by MylesBorins** [comment]
Opened a [PR](https://github.com/nodejs/modules/pull/59) proposing a process for Membership. I think it would be fair to consider your membership in that meeting if we can reach consensus on it.

@weswigham our current Governance for [Team Meetings](https://github.com/nodejs/modules/blob/master/GOVERNANCE.md#team-meetings) seems to imply that the meetings are only for Team Members, although we can invite guests.

> The Team may invite persons or representatives from certain projects to participate in a non-voting capacity.

I'll be the first to admit this is a bit ambiguous, but I personally would prefer to keep meetings to the Team + invited Guests only. Do you think it would make sense to be more specific about it (in either direction)? Perhaps we can move discussion about that to #59 or another issue

**Comment by weswigham** [comment]
> I'll be the first to admit this is a bit ambiguous, but I personally would prefer to keep meetings to the Team + invited Guests only. Do you think it would make sense to be more specific about it (in either direction)? 

That may be so, we've just never enforced it - the meeting links are public and just get posted here. We'd have to distribute meeting materials via another method if we'd like to close them.

**Comment by MylesBorins** [comment]
@weswigham posting the links has always been about transparency and ease of use. If you would like to propose making a more lenient policy I encourage you to open a separate issue.

I'm perfectly fine with us inviting @GeoffreyBooth as an Observer according to the above policy. Which would be as simple as adding them to the agenda when it goes out and giving members a heads up before the meeting (and opportunity to object). I don't think advising an individual to just "show up" is a fair position to put them into and isn't a precedent I think we should set.

**Comment by weswigham** [comment]
> @weswigham posting the links has always been about transparency and ease of use.

So we'd actually turn someone away if they weren't on the membership list? I kinda doubt it (just because I've never seen us take roll beyond self-reporting)? I understand that the membership wants to vet new member additions, but meeting attendance itself has been pretty relaxed. And I'm talking about reality, not some proceedural ideal. I'm not saying that membership requirements and proceedures aren't in place, I'm just saying that there's not been effort applied to keep any interested party out (nor is there much of a difference from being an observer and simply showing up beyond a name on a list). I might not recommend it from a proceedural perspective for our sake, but I am remarking that from a practical perspective nothing stops it. Weather that remark results in us formalizing allowing that possibly, or formalizing a process to prevent it doesn't really matter to me, I'm just pointing out the inconsistency in what we do vs what we say we should be doing.

**Comment by MylesBorins** [comment]
@weswigham as the moderator I have been keeping track of all participants and promote each one to a panelist when they join the call. If someone who was not a member showed up I would ask them to disconnect from the call and to follow a similar process to what @GeoffreyBooth has done in this issue. I wouldn't call anything that has happened up until now in our meeting an inconsistency.

It seems that you have a different reading of our Governance than I do, and that is perfectly fine. What I am trying to suggest is that this issue is not the best place to discuss it, and that encouraging potential new Members to take on unnecessary risk is not fair to them.  I've already mentioned above that we can invite @GeoffreyBooth to come as an Invited Observer to the next meeting if 

A single new issue where we can discuss this ambiguity as a team and come to a conclusion would solve this matter.

**Comment by billinghamj** [comment]
Hmm if you would plan to turn away other people, then I'd request that I am also added to the list of people who are allowed to listen in on discussions.

**Comment by billinghamj** [comment]
Seems a bit non-transparent to require preregistration though.

**Comment by MylesBorins** [comment]
@billinghamj registration is only for individuals who will participate in the conversation. As you mentioned above all meetings are live streamed on youtube and available to be watched afterwards, we also publish meeting notes.

**Comment by MylesBorins** [comment]
If it is helpful, here is the current proposed text for what an "Observer" would be

https://github.com/nodejs/modules/pull/59/files#diff-9e8744ec73212c1966bb19fa22fc3e0aR21

**Comment by billinghamj** [comment]
It might be worth considering adjusting the term, as I would not naturally realise that an observer would be able to speak, etc.

Perhaps “non-voting member” instead?

In any case, for my purposes, I’m happy to remain as an outside observer with no registration 

Appreciate the clarification

**Comment by mcollina** [comment]
+1

**Comment by MylesBorins** [comment]
welcome to the team
