### ISSUE TITLE
Developer Survey

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#85]
We've been making a bunch of claims regarding what "developers would want". While I think we all have quite a great intuition on this, perhaps we can do a developer survey to prove out some of our hypotheses before digging too far into a philosophical debate.

@nodejs/user-feedback can maybe help?

**Comment by mhdawson** [comment]
I think a survey would be a good way to get broader input.  I think this group (the modules wg) would need to put together the initial list of questions to be asked and then the user-feedback team can work with the Greg at the foundation to tweak and then have the survey run.

**Comment by mhdawson** [comment]
As an example, its good that the questions be closed whenever possible.

How important is interop between CJS and EJS to you:

1 - not at all
2 - small benefit
3 - nice to have
4 - important
5 - top priority

**Comment by ljharb** [comment]
For that specific question (and probably many others), we should also *separately* ask how important that feature is to be available *by default* versus "by a loader" versus "not at all"

**Comment by jkrems** [comment]
> "by a loader"

nit: How about "enabled by default" vs. "possible" or "opt-in"? Mostly because loader might be hard to understand for people / might imply too much.

**Comment by bmeck** [comment]
I think we need to be sure that we encapsulate the questions so that we are clearly trying to get either the *expectation* of how ESM would be implemented, or the *opinion* of if a feature is important. I think it is very easy to be unclear on the difference of these. Expectations can lead to opinions of if a feature is important, but they are not necessarily the same thing. You can have a neutral opinion while having a strong expectation of how things should work.

Defining what interop is is a complex task for example. Consider the following points and how detailed I think we need to be in order to start to expose this difference:

* how important is it to be able to load ESM from CJS
* would you expect to be able to use `import(ESM)` to load ESM from CJS
* would you expect to be able to use `require(ESM)` to load ESM from CJS
* how important is it `require(ESM)` is synchronous and does not return a Promise

Even after all of this, we might have comflicts with implementing some features such as synchronously returning a module namespace from `require`. These questions are used as guides for what users are thinking, and we need to be clear about if they are thinking in terms of expectation and if they are thinking in terms of opinions of a feature's value.

**Comment by bmeck** [comment]
Oh, and we should probably figure out what questions each feature needs so maybe that is a good place to maybe start making a list of questions and combining similar ones as we go along? Does that seem a good idea to others?

**Comment by mhdawson** [comment]
@bmeck sounds reasonable to me.

**Comment by inidaname** [comment]
@bmeck I +1, also I will suggest we use the Google Doc from #55 as a guide for generating a more kind of specific questions.

**Comment by SMotaal** [comment]
Any interested in reviving this effort?

I independently started to work on an iterative survey building effort, which starts with the premise that while I know to some degree the composition of the participants that I am interested in surveying, I still don't know exactly what type of questions will elicit the more informative and reliable results. 

From there the survey will be iteratively built by getting two participants (starting with the group) to take the survey then provide recommendations and feedback (privately) which will be incorporated and peer reviewed by those who have already taken it, and so on.

It is common practice that drafts would be shared openly, and obviously this will happen, but after we all had a chance to somewhat anonymously contribute to the resulting initial draft.

I am looking for the first two participants, the survey is very raw and likely not on point at all, but that is naturally going to change especially if you take part.

**Comment by SMotaal** [comment]
@sendilkumarn  Are you interested? If so you can take a go at the first round and once we refine it you can also weigh in on changes as we move forward.

We will still need at least one more participant to carry out the first round.

**Comment by sendilkumarn** [comment]
Lets do it 👍

**Comment by SMotaal** [comment]
Please jump over to #173 regarding efforts to prepare Initial Draft (set to unroll for October's event)

**Comment by MylesBorins** [comment]
We've discussed this at multiple meetings, removing from agenda for now.

**Comment by spitWind** [comment]
同步导入 浏览器,node.js 的一些设想
```

(async function (exports, require, module, __filename, __dirname, process, global, Buffer, cache) {
  // let cache = {}
  let require = function (name) {// 相对路径
    //  略
    return cache[name]
  }
  let modules = ["./data", "./test"]
  await modules.forEach(
    async function (key) {
      cache[key] = await import(key)
    }
  ) // chrome 静态分析 require 依赖 // 异步加载

  return function (exports, module, __filename, __dirname) {
    // require（）


  }
    .call(this, exports, require, module, __filename, __dirname);
}
);
```
